### ISSUE TITLE
Building and installing doesn't work properly

### ISSUE THREAD

**Issue by AlphaCraft9658** [boehs/Lightly#4] opened 2023-01-10 17:44 UTC
The building and installation themselves work with no issues, but once I try to use the Lightly theme built from here, system settings tell me that this theme can't be used.

**Comment by boehs** [comment] 2023-01-10 21:17
1. Does it work with normal lightly?
2. KDE & KDE frameworks version?
3. Any errors/warnings during build?
4. Please send a screenshot of the message you described

Thanks

**Comment by AlphaCraft9658** [comment] 2023-01-27 14:03
> 1. Does it work with normal lightly?
> 2. KDE & KDE frameworks version?
> 3. Any errors/warnings during build?
> 4. Please send a screenshot of the message you described
> 
> Thanks

When manually building Lightly, even from the original repo, plasma settings can't apply the theme.

**Comment by boehs** [comment] 2023-01-27 17:24
I have absolutely no clue how to reproduce this then. At the least, I'd like that other information I've requested

**Comment by AlphaCraft9658** [comment] 2023-02-01 16:36
> I have absolutely no clue how to reproduce this then. At the least, I'd like that other information I've requested

KDE-Version: 2.26.6
KDE-Frameworks-Version: 5.102.0

There are some warnings, that I get during the "make" command.

![image](https://user-images.githubusercontent.com/77483478/216104574-a09984ca-0884-4b75-94ed-020a0f4ce7fd.png)

My system language is set to German. The message translates to "The selected style "Lightly" can't be applied".

**Comment by ThakshilaDamsak** [comment] 2023-02-13 14:41
I have the same problem.

KDE Plasma Version: 5.26.5
KDE Frameworks Version: 5.102.0
Qt Version: 5.15.8
Kernel Version: 6.1.10-1-default (64-bit)

![Screenshot_20230213_200801](https://user-images.githubusercontent.com/95128171/218487698-db79d24b-e306-4177-b1f2-6a8149a091e7.png)

**Comment by kturques** [comment] 2023-03-03 21:58
When building on OpenSuse, I have to change "CMAKE_INSTALL_LIBDIR" from lib to lib64.
Like this:

`cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_LIBDIR=lib64 -DBUILD_TESTING=OFF ..`

Don't know if it helps

**Comment by boehs** [comment] 2023-03-15 01:03
@kturques sorry I missed this. Facinating. How did you discover?

**Comment by kturques** [comment] 2023-03-17 10:56
Thats where breeze store its libs in OpenSuse
```
usr
└── lib64
    ├── cmake
    │   └── Breeze
    │       ├── BreezeConfig.cmake
    │       └── BreezeConfigVersion.cmake
    ├── kconf_update_bin
    │   ├── breezehighcontrasttobreezedark
    │   ├── breezetobreezeclassic
    │   └── breezetobreezelight
    └── qt5
        └── plugins
            ├── plasma
            │   └── kcms
            │       └── systemsettings_qwidgets
            │           └── breezestyleconfig.so
            └── styles
                └── breeze.so
```
And Lightly:

```
usr
└── lib64
    ├── cmake
    │   └── Lightly
    │       ├── LightlyConfig.cmake
    │       └── LightlyConfigVersion.cmake
    ├── kconf_update_bin
    │   └── kde4lightly
    ├── liblightlycommon5.so.0.43
    ├── liblightlycommon5.so.5 -> liblightlycommon5.so.0.43
    └── qt5
        └── plugins
            ├── kstyle_lightly_config.so
            ├── org.kde.kdecoration2
            │   └── lightlydecoration.so
            └── styles
                └── lightly.so
```

**Comment by MineBill** [comment] 2023-03-30 15:06
I also experienced the same problem on Fedora 38 and i managed to fixed it by installing dependencies that were marked as OPTIONAL by CMake. I initially assumed they weren't needed because CMake didn't block the build(as it did with some other dependencies i was missing). The packages i was missing:
* kf5-kcmutils-devel
* kf5-frameworkintegration-devel

**Comment by raphipod** [comment] 2023-04-07 22:34
> When building on OpenSuse, I have to change "CMAKE_INSTALL_LIBDIR" from lib to lib64. Like this:
> 
> `cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_LIBDIR=lib64 -DBUILD_TESTING=OFF ..`
> 
> Don't know if it helps

Tested the cmake flag on Nobara Linux (Fedora 37), it worked and the Lightly theme is now applicable in the Application styles without errors.

**Closed** 2023-04-08 02:09 UTC
